comment: false

ignore:
  - "**/DATASET.*"
  - "**/Fisher_*"
  - "**/benchmarking_and_testing.*"
  - "**/HR_interpolation.*"
  - "^tests/benchmarking_and_testing\.R$"
  - "^tests/HR_interpolation\.R$"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
