comment: false

ignore:
  - "**/DATASET.*"
  - "**/Fisher_*"
  - "**/benchmarking_and_testing.*"
  - "**/HR_interpolation.*"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
